# Generated by Django 4.0.1 on 2022-02-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('blockchain', models.TextField(max_length=100)),
            ],
        ),
    ]
