# Generated by Django 4.0.1 on 2022-02-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='owner',
            field=models.CharField(default='Marianne Salamanca', max_length=100),
        ),
        migrations.AlterField(
            model_name='nft',
            name='blockchain',
            field=models.CharField(max_length=100),
        ),
    ]
