# Generated by Django 4.0.1 on 2022-02-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_nft_owner_alter_nft_blockchain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='owner',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
