# Generated by Django 4.0.1 on 2022-02-05 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_nft_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Selling Date')),
                ('sell', models.CharField(choices=[('Se', 'Selling'), ('So', 'Sold')], default='Se', max_length=2)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nft')),
            ],
        ),
    ]
